spring:
  application:
    name: Spring
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pramod#12
    url: jdbc:mysql://localhost:3306/springbatch
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hivralepramod4@gmail.com
    password: ceav fwpu awgl ixza
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
